### ISSUE TITLE
No Module

### ISSUE THREAD

**Issue by SussyMirani** [dgigstv/nbs-viewer#1]
when i try to install module it says
404 Not Found - GET https://registry.npmjs.org/dgigs-lint/-/dgigs-lint-1.0.0.tgz - Not found
![image](https://user-images.githubusercontent.com/57767778/156803777-5a632d6a-fe8e-4316-af52-6821b8a38434.png)

**Comment by dgigstv** [comment]
Thanks for the report! I removed the offending package and bumped versions for the linting and testing stuff.
